### ISSUE TITLE
System requirements?

### ISSUE THREAD

**Issue by ghost** [jankais3r/DNoiSe#4]
First of all: idk if I'm doing something wrong.
I just started it on my 3a+ and it ran out of memory, does it take so much memory?
I have only pihole and unbound installed.

**Comment by jankais3r** [comment]
The only memory intensive part is extracting the ZIP file and loading it into a SQLite database. And since this part runs fine on my 1st gen raspberry, I am pretty sure your problem is not causes by the script. But you can try running it on your machine to generate the domain.db file and then put it on your raspberry. Then it definitely should not cause any memory issues.

**Comment by ghost** [comment]
Yep! I am so sorry to have opened this issue... now it runs fine!

**Comment by jankais3r** [comment]
No worries, happy it works now 🙂
